apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.DOCKER_REGISTRY}}/gitcoinco/web:{{.VERSION}}"
  artifacts:
    - imageName: gitcoin-web
      workspace: .
      docker: { }
  local: { }
deploy:
  kubectl:
    manifests:
profiles:
  - name: dev
    build:
      tagPolicy:
        envTemplate:
          template: "{{.DOCKER_REGISTRY}}/gitcoinco/web:{{.DIGEST_HEX}}"
      artifacts:
        - image: none
          docker: { }
      local: { }
    deploy:
      helm:
        releases:
          - name: web
            chartPath: charts/web
            setValueTemplates:
              image.repository: "{{.DOCKER_REGISTRY}}/gitcoinco/web"
              image.tag: "{{.DIGEST_HEX}}"
