name: Check Markdown links

on:
  pull_request:
    paths: "**.md"

jobs:
  lint-md:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install --legacy-peer-deps
      - run: npx remark --use validate-links . .github
