name: Auto-merge Dependabot PRs

on:
  schedule:
    - cron: "0 * * * *"

jobs:
  auto_merge:
    name: Auto-merge Dependabot PRs
    runs-on: ubuntu-latest
    steps:
      - uses: akheron/dependabot-cron-action@a8dab4aadf1720593c756a86a3d2845e58197cba
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          auto-merge: "minor"
          merge-method: "squash"
