name: Release Flow

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version to release (optional)
        required: false
      force:
        description: Force a release even when there are release-blockers (optional)
        required: false
  schedule:
    # We want the release to be at 10 or 11am Pacific Time
    - cron: "0 18 15 * *"

jobs:
  release:
    runs-on: ubuntu-latest
    name: "Release a new version"
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GIHUB_TOKEN }}
          fetch-depth: 0
      - name: Prepare release
        uses: getsentry/action-prepare-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GIHUB_TOKEN }}
        with:
          version: ${{ github.event.inputs.version }}
          force: ${{ github.event.inputs.force }}
          calver: true
