name: 'Tests: shellcheck'

on: [ pull_request, push ]

jobs:
  shellcheck_matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        shell:
          - bash
          - sh
          - dash
          - ksh
        file:
          - ./scripts/nvm.sh
        include:
          - shell: bash
            file: ./scripts/install.sh # only supported on bash
          - shell: bash
            file: ./scripts/release.sh # only needed in bash/zsh

    steps:
      - uses: actions/checkout@v2
      - name: Install shellcheck
        run: brew install shellcheck
      - run: "shellcheck --version"
      - name: Run shellcheck on ${{ matrix.file }}
        run: shellcheck -s ${{ matrix.shell }} ${{ matrix.file }}

  shellcheck:
    needs: [ shellcheck_matrix ]
    runs-on: ubuntu-latest
    steps:
      - run: 'echo tests completed'
